# Model arguments
model_name_or_path: /mnt/bn/brench-volume-lq1/graduation_design/GRPO-R1-Training-RL/X-R1/models/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: Brench/R1-Zero-GRPO-750
dataset_configs:
- train
num_processes: 1

# GRPO trainer config

bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.10
do_eval: false
eval_strategy: "no"
eval_steps: 10
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
num_generations: 4
max_completion_length: 4096
max_steps: -1
num_train_epochs: 2
output_dir: output/Qwen2.5-0.5B-R1-GRPO-V1
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4

push_to_hub: False
report_to:
- wandb
wandb_project: Brench-Qwen2.5-GPRO-R1-ZERO
wandb_entity: Qwen2.5-GPRO-R1-ZERO-TEST-v2
run_name: Qwen2.5-GPRO-R1-ZERO-TEST-v2
save_strategy: "steps"
save_steps: 200
seed: 42
warmup_ratio: 0.1
