# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  4x3090(24G)/4090(24G)
# running time 2~3h

# Model arguments
model_name_or_path: /mnt/bn/brench-volume-lq1/graduation_design/GRPO-R1-Training-RL/models/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: Brench/R1-Zero-GRPO-7500
dataset_configs:
- train
num_processes: 1

# GRPO trainer config

bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.15
do_eval: false
eval_strategy: "no"
eval_steps: 10
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 2048
num_generations: 2
max_completion_length: 8192
max_steps: -1
num_train_epochs: 2
output_dir: output/Qwen2.5-1.5B-R1-GRPO-V1
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2

push_to_hub: False
report_to:
- wandb
wandb_project: Brench-Qwen2.5-GPRO-R1-ZERO
wandb_entity: Qwen2.5-GPRO-R1-ZERO-TEST-v1
save_strategy: "steps"
save_steps: 200
seed: 42
warmup_ratio: 0.1
